NOOP
MUTEX_CREATE MUTEX_1
MUTEX_CREATE MUTEX_2
MUTEX_CREATE MUTEX_3
NOOP
NOOP
INIT_PROC PHP_1.prc 5
INIT_PROC PHP_2.prc 4
NOOP
INIT_PROC PHP_3.prc 3
INIT_PROC PHP_3.prc 3
INIT_PROC PHP_3.prc 3
INIT_PROC PHP_3.prc 3
INIT_PROC PHP_3.prc 3
NOOP
INIT_PROC PHP_4.prc 2
NOOP
NOOP
INIT_PROC PHP_5.prc 1
EXIT